# templates/service.yaml
{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.serviceName }}
  labels:
    app: {{ .Values.proxy.serviceName }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.proxy.containerPort }}
      targetPort: {{ .Values.proxy.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.proxy.serviceName }}
{{- end }}
