apiVersion: v1
data:
  keycloak.crt: |
    # -----BEGIN CERTIFICATE-----

    # -----END CERTIFICATE-----
  server.cnf: |
    [req]
    prompt = no
    x509_extensions = req_ext
    distinguished_name = dn

    [dn]
    CN = 172.1.2.3

    [req_ext]
    subjectAltName = @alt_names
    basicConstraints = CA:TRUE
    keyUsage = keyCertSign, digitalSignature, keyEncipherment

    [alt_names]
    DNS.1 = localhost
    DNS.2 = keycloak
  server.crt: |
    # -----BEGIN CERTIFICATE-----

    # -----END CERTIFICATE-----
  server.key: |
    # -----BEGIN PRIVATE KEY-----
    
    # -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  labels:
    app: backend
  name: backend-cm0
