apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.keycloak.serviceName }}
  name: {{ .Values.keycloak.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.keycloak.serviceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.keycloak.serviceName }}
    spec:
      containers:
        - image: {{ .Values.keycloak.image }}
          name: {{ .Values.keycloak.containerName}}
          imagePullPolicy: {{ .Values.keycloak.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.keycloak.targetPort }}
              protocol: TCP
          env:
          {{- range $key, $value := .Values.keycloak.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          
          volumeMounts:
            # - name: keycloak-data
            #   mountPath: /opt/keycloak/data
            - name: keycloak-tls
              mountPath: /opt/keycloak/conf/keycloak.crt
              subPath: tls.crt
            - name: keycloak-tls
              mountPath: /opt/keycloak/conf/keycloak.key
              subPath: tls.key

      restartPolicy: Always

      volumes:
        # - name: keycloak-data
        #   persistentVolumeClaim:
        #     claimName: keycloak-data

        - name: keycloak-tls
          secret:
            secretName: keycloak-tls
