apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.keycloak.serviceName }}
  name: {{ .Values.keycloak.serviceName }}
spec:
  type: ClusterIP
  ports:
    - name: "8443"
    # port is hardcoded to 8443 to access keycloak directly
      port: {{ .Values.ingress.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }}
      protocol: TCP
  selector:
    app: {{ .Values.keycloak.serviceName }}
