# templates/deployment.yaml
spec:
  template:
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "myproxy.fullname" . }}-config
        - name: tangy-tls-secret
          secret:
            secretName: tangy-tls-secret # The secret you created in Step 1
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 443
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: tangy-tls-secret
              mountPath: /etc/nginx/certs
              readOnly: true

