apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.postgres.serviceName }}
  name: {{ .Values.postgres.serviceName }}
spec:
  ports:
    - name: "5432"
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: {{ .Values.postgres.serviceName }}
