replicas: 1
host: 127.0.0.1

ingress:
  enabled: false
  frontendHost: tangy.local
  backendHost: tangy.local

  

proxy:
  enabled: true
  serviceName: nginx-proxy
  image: nginx:1.26
  imagePullPolicy: IfNotPresent
  containerName: nginx-proxy
  containerPort: 443
  host: tangy.local
  tlsSecretName: server-tls
  frontendService: frontend
  frontendPort: 4173
  backendService: backend
  backendPort: 5000

frontend:
  serviceName: frontend
  image: tm-rfo-frontend:test
  imagePullPolicy: IfNotPresent
  containerName: xbi-frontend-trial

  # port: 443
  # targetPort: 5173
  port: 4173
  targetPort: 4173
  probes:
    enabled: true

  env:
    # VITE_BACKEND_URL: {{printf "https://backend:%d" .Values.backend.port}}
    VITE_BACKEND_URL: "https://tangy.local/api"
    VITE_CLIENT_ID: xbi-tasking-frontend
    VITE_KEYCLOAK_REALM: xbi-tasking
    # VITE_KEYCLOAK_URL: "https://tangy.auth.local:8443"
    VITE_KEYCLOAK_URL: "https://tangy.auth.local:8443"
    VITE_MUI_X_LICENSE_KEY: e0d9bb8070ce0054c9d9ecb6e82cb58fTz0wLEU9MzI0NzIxNDQwMDAwMDAsUz1wcmVtaXVtLExNPXBlcnBldHVhbCxLVj0y

backend:
  serviceName: backend
  image: tm-rfo-backend:latest
  imagePullPolicy: IfNotPresent
  containerName: xbi-backend-trial
  # gateway:
  #   enabled: true
  #   hostnames: 

  # port: 5000
  port: 5000

  env:
    ALLOWED_CLIENT_IDS: xbi-tasking-frontend, xbi-tasking-backend, xbi-tasking-admin
    AUTO_INIT_DB: "true"
    HOST: 0.0.0.0
    SSL_CERTFILE: /certs/server.crt
    SSL_KEYFILE: /certs/server.key
    KEYCLOAK_CA_BUNDLE: /certs/keycloak.crt
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
    # CORS_ORIGINS: "https://tangy.local:4173,http://tangy.local:4173,http://localhost:4173"
    CORS_ORIGINS: "https://tangy.local,http://tangy.local:4173,http://localhost:4173"
    # DB_HOST: {{ .Values.postgres.serviceName }}
    # DB_NAME: {{ .Values.postgres.env.POSTGRES_DB }}
    # DB_PASSWORD: {{ .Values.postgres.env.POSTGRES_PASSWORD }}
    # DB_PORT: {{ .Values.postgres.port }}
    # DB_USER: {{ .Values.postgres.env.POSTGRES_USER }}
    DB_HOST: postgres
    DB_NAME: XBI_TASKING_3
    DB_PASSWORD: password
    DB_PORT: 5432
    DB_USER: postgres
    # FRONTEND_URL: https://172.1.2.3:5173
    # FRONTEND_URL: https://tangy.local:4173
    FRONTEND_URL: https://tangy.local
    KEYCLOAK_ADMIN_CLIENT_ID: xbi-tasking-admin
    KEYCLOAK_ADMIN_CLIENT_SECRET: cj5bXh8YM42AJlLiozwlxGFNLLhwbzr3
    KEYCLOAK_CLIENT_ID: xbi-tasking-backend
    KEYCLOAK_CLIENT_SECRET: xyaImNvxSnD8lgQ3qK2yyKuCuZG3ZbvM
    KEYCLOAK_ENABLED: "true"
    # KEYCLOAK_INTERNAL_URL: https://keycloak:8443
    # KEYCLOAK_PUBLIC_URL: https://tangy.auth.local:8443
    KEYCLOAK_PUBLIC_URL: https://tangy.auth.local:8443
    KEYCLOAK_REALM: xbi-tasking
    ALLOWED_CLIENT_IDS: "xbi-tasking-frontend, xbi-tasking-backend, xbi-tasking-admin"
    ROLES_CLIENT_ID: xbi-tasking-backend
    REQUIRED_GROUP: xbi-tasking-users

# keycloak:
#   serviceName: keycloak
#   # image: tm_v3-keycloak:latest
#   image: xbi-keycloak:test
#   imagePullPolicy: IfNotPresent
#   containerName: xbi-keycloak-trial

#   port: 8443
#   targetPort: 8443

#   storage:
#     size: 1Gi

#   env:
#     KC_BOOTSTRAP_ADMIN_USERNAME: admin
#     KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#     # KC_PROXY_HEADERS: xforwarded
#     KC_PROXY: edge
#     KC_HOSTNAME: tangy.auth.local
#     KC_HOSTNAME_STRICT: false
#     KC_HTTP_ENABLED: true


postgres:
  serviceName: postgres
  image: postgres:15.6
  imagePullPolicy: IfNotPresent
  containerName: xbi-postgres-trial

  storage:
    size: 1Gi

  port: 5432
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: XBI_TASKING_3

# gateway:
#   enabled: true
#   name
