# templates/config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  # Frontend runtime config
  config.js: |
    window.APP_CONFIG = {
      backendUrl: '{{ .Values.frontend.env.VITE_BACKEND_URL }}',
      keycloak: {
        url: '{{ .Values.frontend.env.VITE_KEYCLOAK_URL }}',
        realm: '{{ .Values.frontend.env.VITE_KEYCLOAK_REALM }}',
        clientId: '{{ .Values.frontend.env.VITE_KEYCLOAK_CLIENT_ID }}',
        rolesClientId: '{{.Values.frontend.env.VITE_ROLES_CLIENT_ID }}'
      },
    };
  
  # Nginx configuration
  nginx.conf: |
    worker_processes auto;
    error_log /dev/stderr warn;
    pid /tmp/nginx.pid;
    
    events {
        worker_connections 1024;
    }
    
    http {
        log_format main '$remote_addr - $remote_user [$time_local] "$request"' '$status $body_bytes_sent "$http_referer"' '"$http_user_agent"';
        access_log /dev/stdout main;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path /tmp/proxy_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;
        access_log /tmp/access.log;
        
        client_max_body_size 500M;
        
        upstream backend {
            server backend:5000;
        }
        
        server {
            listen 8080;
            root /usr/share/nginx/html;
            index index.html;
            # ssl_certificate /certs/tls.crt;
            # ssl_certificate_key /certs/tls.key;

            # Frontend static files
            location / {
                try_files $uri $uri/ /index.html;
                # proxy_pass http://backend;
                # proxy_set_header Host $host;
                # proxy_set_header X-Real-IP $remote_addr;
                # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                # proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
    